services:
  app:
    build:
      context: . 
      dockerfile: InstantMessagingApp.WebApi/Dockerfile
    container_name: chat_api
    restart: always
    ports:
     - "8080:8080"
    environment:
      DEFAULT_CONNECTION: Host=postgres;Database=ChatMessageDb;Username=postgres;Password=postgres
      TELEGRAM__BOTTOKEN: ${TELEGRAM__BOTTOKEN}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
  
  postgres:
    image: postgres:15
    container_name: chatMessage_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ChatMessageDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
      
volumes:
  db_data: