services:
  app:
    build:
      context: . .
      dockerfile: InstantMessagingApp.WebApi/Dockerfile
    container_name: chat_api
    ports:
     - "8080:8080"
    environment:
      DEFAULT_CONNECTION: Host=postgres;Database=ChatMessageDb;Username=postgres;Password=postgres
    env_file:
      - .env
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15
    container_name: chatMessage_postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    
    